## Sintaxe Básica Python

A sintaxe básica também pode ser encontrada nos slides ([Python 1](https://daniel-hasan.github.io/cefet-web-grad/classes/python1/) e [Python 2](https://daniel-hasan.github.io/cefet-web-grad/classes/python2/)) e na [documentação da linguagem](https://www.python.org/doc/).

### Variáveis e tipos em Python

Variáveis não são declaradas e, a partir do momento que usamos, começam a existir.

In [2]:
x = 1
y = "oi"
print(x)
print(type(x))

print(y)
print(type(y))

1
<class 'int'>
oi
<class 'str'>


No Jupyther notebook, você pode editar o código e executá-lo (apertando ctrl+enter dentro do mesmo) a vontade. Fique atento apenas com a ordem de execução.

### Listas

Listas são estruturas de dados unidimensionais, **heterogêneas**. 

In [2]:
lista_de_coisas = ['Aew', 35, True, [], 'outra string']
print(len(lista_de_coisas)) #len retorna o tamanho da lista
print(lista_de_coisas[0]) #imprime "Aew"
l = [4,2,5]
l.sort()
print(l)

5
Aew
[2, 4, 5]


Veja mais sobre operações úteis em strings e listas [nos slides](https://daniel-hasan.github.io/cefet-web/classes/python2/#string_lista)

#### Sublistas

Como obter divisões de listas e matrizes

In [3]:
#Inicialização das variáveis deste exemplo
vetor = [1,2,4,21,4,2,5]
inicio = 1
fim = 4

#vetor com as posições 0..fim (exceto a posição fim)
subvet = vetor[:fim] 
print("vet 0..fim: "+str(subvet))
#vetor com as posições inicio..fim (exceto a posição fim)
subvet = vetor[inicio:fim] 
print("vet inicio..fim: "+str(subvet))

#vetor com as posições inicio..ultima posição
subvet = vetor[inicio:] 
print("vet inicio..ultima posição: "+str(subvet))

vet 0..fim: [1, 2, 4, 21]
vet inicio..fim: [2, 4, 21]
vet inicio..ultima posição: [2, 4, 21, 4, 2, 5]


In [4]:
#numpy é uma biblioteca que auxilia ao criarmos vetores e matrizes numéricas
#inclusive, essa biblioteca aumenta a perfomance para operações com vetores e matrizes numéricas
#importante que seja numpy, pois, caso contrário, não seria possivel filtrar colunas
import numpy as np
#para dividirmos em colunas, temos que usar o numpy
MATRIZ = np.array([[1,2,3],
                   [5,3,2],
                   [2,5,3],
                   [4,3,2],
                   [1,6,2],
                   [7,7,2]])
inicio = 1
fim = 4

#igual vetor, com as linhas 0..fim (exceto a posição fim)
SUB_MATRIZ = MATRIZ[:fim]
print("matriz 0..fim:"+str(SUB_MATRIZ))

#primeira coluna da linha inicio..fim (exceto linha fim) 
SUB_MATRIZ = MATRIZ[inicio:fim,0]
print("matriz[inicio..fim,0]: "+str(SUB_MATRIZ))

#as duas primeiras colunas da linha inicio até o final 
SUB_MATRIZ = MATRIZ[inicio:,:2]
print("matriz[inicio..fim,0:2]: "+str(SUB_MATRIZ))

matriz 0..fim:[[1 2 3]
 [5 3 2]
 [2 5 3]
 [4 3 2]]
matriz[inicio..fim,0]: [5 2 4]
matriz[inicio..fim,0:2]: [[5 3]
 [2 5]
 [4 3]
 [1 6]
 [7 7]]


### Dicionários

Dicionários são estruturas de mapeamento chave-valor em que a chave é [qualquer tipo imutável](https://towardsdatascience.com/https-towardsdatascience-com-python-basics-mutable-vs-immutable-objects-829a0cb1530a) o valor pode ser qualquer tipo em Python. Em outras linguagens essa estrutura de dados é chamada de **vetor associativo**. Esse estrutura se ao objeto JavaScript. 

In [5]:
x = {} #inicia um dicionário vazio
x['Alice'] = 3
x[23] = 5
x[32,32] = 10# x = {(32, 32): 10, 'Alice': 3, 23: 5}
idc_remissivo = {'casa':[1,3],'verde':[3,5,6]}
idc_remissivo['casa'].append(7) 
print("=== x ===")
print(x)
print("=== idc remissivo ==")
print(idc_remissivo)

=== x ===
{'Alice': 3, 23: 5, (32, 32): 10}
=== idc remissivo ==
{'casa': [1, 3, 7], 'verde': [3, 5, 6]}


In [6]:
from datetime import datetime #inclusão do módulo datetime
voo = {
    'companhia': 'Gol',
    'numero': 815,
    'decolagem': {
        'IATA': 'SYD',
        'horario': datetime(2005, 7, 14, 12, 30),#
        'cidade': 'Sydney'
    },
    'chegada': {
        'IATA': 'LAX',
        'horario': datetime(2005, 7, 14, 15, 30),
        'cidade': 'Los Angeles'
    }
}

print(voo['decolagem']['horario'])

2005-07-14 12:30:00


 Veja mais sobre estrutura de dados [nos slides](https://daniel-hasan.github.io/cefet-web/classes/python2/#mais-colecoes) e [na documentação](https://docs.python.org/2/tutorial/datastructures.html)

### Statements

#### Condicionais

Usamos as clausulas abaixo para condicionais simples e compostas. Veja que podemos usar o **elif** para fazer o equivalente a um **switch**.

Perceba também que os blocos de comandos são definidos por identação.

In [4]:
hora = 6
if hora >= 5 and hora < 12:
    print("Bom dia!")
else:
    print("Não está de manha.")

Bom dia!


In [5]:
hora = 15
if(hora >= 5 and hora <12):
    print("Bom dia!")
elif(hora >= 12 and hora < 19):
    print("Boa tarde!")
else:
    print("Boa noite!")

Boa tarde!


### Funções

Funções são declaradas usando o termo `def`:

In [6]:
def add(a, b):
  return a + b

x = add(2,5)  
print(x)

7


As seguintes chamadas à função possui o mesmo resultado:

In [7]:
x = add(a=2,b=5)
print("X="+str(x))
x = add(2,b=5)
print("X="+str(x))

X=7
X=7


a=2 e b=5 são **keyword arguments** e, os demais, **Positional Arguments**. Não é possível colocar keyword arguments e, logo após, Positional Arguments:



In [8]:
x = add(a=2,5)

SyntaxError: positional argument follows keyword argument (<ipython-input-8-29055e0d42b6>, line 1)

Pode-se definir **valores default para argumentos**. Assim, estes argumentos podem ser omitidos na hora de invocar a função:

In [9]:
def add(a, b=1, c=0):
  return a + b + c

x = add(2,5,1)   # x = 8
print("add(2,5,1) = "+str(x))

x = add(2,5)     # x = 7
print("add(2,5) = "+str(x))

x = add(2)     # x = 3
print("add(2) = "+str(x))

x = add(2,c=2)     # x = 5
print("add(2,c=2) = "+str(x))

add(2,5,1) = 8
add(2,5) = 7
add(2) = 3
add(2,c=2) = 5


### Estrutura de repetição simples

Imprima os valores de **i** a seguir usando a estutura de repetição [presente neste slide](https://daniel-hasan.github.io/cefet-web/classes/python1/#18). 

In [10]:
### Seu código aqui: De i=0; enquanto i<10

for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [11]:
### Seu código aqui: De i=3; enquanto i<9; passo 2:

for i in range(3, 9, 2):
    print(i)

3
5
7


In [12]:
### Seu código aqui: De i=6; enquanto i<1; passo -2:

for i in range(6, 1, -2):
    print(i)

6
4
2


### Estrutura de repetição - percorrendo listas

Considere a seguinte lista:

In [13]:
itens = ["bola", "chuteira", "luvas"]

Percorra a lista imprimindo também os índices [veja slide](https://daniel-hasan.github.io/cefet-web/classes/python1/#19)

In [14]:
### Seu código aqui

for i, item in enumerate(itens):
    print(f"{i}: {item}")

0: bola
1: chuteira
2: luvas


Percorra sem precisar de obter o índice

In [15]:
### Seu código aqui

for item in itens:
    print(item)

bola
chuteira
luvas


### Estrutura de Repetição  - percorrendo dicionários

Considere o dicionário abaixo, percorra ele imprimindo sua chave e valor [veja slides](https://daniel-hasan.github.io/cefet-web/classes/python2/#15)

In [16]:
x = {"Alice":16, "Bob":19, "Carol": 20, "Débora":21}
 
## Seu código aqui

for chave, valor in x.items():
    print(f"{chave}: {valor}")

Alice: 16
Bob: 19
Carol: 20
Débora: 21


Crie um vetor de dicionário (use a criatividade) e percorra-o imprimindo, para cada posição do vetor, o valor de todas as chaves (faça um for também navegando nas chaves/valor para isso). 

In [ ]:
### Seu código aqui

